### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by sleipnir** [dlesl/erqwest#16]
Hello, first I would like to congratulate you on the excellent project!
I would also like to know if this project is still active? And is it safe to use it in production?

**Comment by dlesl** [comment]
Hi, @sleipnir, thanks! I'm not currently planning on doing any more work on the project, since it now does everything I wanted from an HTTP client, but feel free to open an issue if anything you need is missing. I'm not aware of anyone using it in production, and it's not in any way what I would consider battle tested. If you need something that is, consider [katipo](https://github.com/puzza007/katipo). But if you decide you need to go faster/need the extra streaming/async features in erqwest do let me know how it goes :)

**Comment by sleipnir** [comment]
> Hi, @sleipnir, thanks! I'm not currently planning on doing any more work on the project, since it now does everything I wanted from an HTTP client, but feel free to open an issue if anything you need is missing. I'm not aware of anyone using it in production, and it's not in any way what I would consider battle tested. If you need something that is, consider [katipo](https://github.com/puzza007/katipo). But if you decide you need to go faster/need the extra streaming/async features in erqwest do let me know how it goes :)

Thanks for answering.
We are testing the use of your library in our [Spawn project](https://github.com/eigr/spawn). Let's see how it behaves.

**Comment by dlesl** [comment]
Nice!
