### ISSUE TITLE
Validating options passed to make_client/2

### ISSUE THREAD

**Issue by puzza007** [dlesl/erqwest#5]
What do you think about validating the options passed to `make_client/2`? I was thinking this could be done in Erlang rather than Rust? Would you prefer a `badarg` or to change the return value to `{ok, Client} | {error, Reason}`.

**Comment by dlesl** [comment]
I think this is a great idea! I really like this feature in `katipo`, because a flag being silently ignored can be pretty hard to track down, and dialyzer might not always catch it :smile: 

My preference is to go with `badarg` for programmer errors and `{error, Reason}` for something you could handle at runtime, so for `make_client/2` I think `badarg` would be best. Maybe in the future there could be an option that's only available sometimes which you might want to handle at runtime, but then we could go with a solution like katipo's `xxx_available/0` exports, since these are likely to be rarely used.
